version: "3"

services:
  namenode:
    image: ba/hadoop
    command: start-hadoop namenode
    networks:
      - backend
    volumes:
      - hdfs:/opt/hdfs
    ports:
      - "8020:8020"
      - "14000:14000"
      - "50070:50070"
      - "50075:50075"
      - "10020:10020"
      - "13562:13562"
      - "19888:19888"

  resourcemanager:
    image: ba/hadoop
    command: start-hadoop resourcemanager
    networks:
      - backend
    volumes:
      - hdfs:/opt/hdfs
    ports:
      - "8032:8032"
      - "8033:8033"
      - "8040:8040"
      - "8088:8088"

  datanode_nodemanager:
    image: ba/hadoop
    command: start-hadoop datanode
    networks:
      - backend
    depends_on:
      - resourcemanager
      - namenode

  edge:
    image: ba/edge
    tty: true # keep container without running main process
    networks:
      - backend
      - frontend
    depends_on:
      - resourcemanager
      - namenode

volumes:
  hdfs:

networks:
  frontend:
  backend:
