version: "3"

services:
  namenode:
    image: maiktheknife/hadoop
    command: start-hadoop namenode
    hostname: namenode
    networks:
      - backend
    ports:
      - "8020:8020"
      - "14000:14000"
      - "50070:50070"
      - "50075:50075"
      - "10020:10020"
      - "13562:13562"
      - "19888:19888"
    deploy:
      mode: global

  resourcemanager:
    image: maiktheknife/hadoop
    command: start-hadoop resourcemanager
    hostname: resourcemanager
    networks:
      - backend
    ports:
      - "8032:8032"
      - "8033:8033"
      - "8040:8040"
      - "8088:8088"
    deploy:
      mode: global

  datanode:
    image: maiktheknife/hadoop
    command: start-hadoop datanode
    networks:
      - backend
    depends_on:
      - namenode
    deploy:
      mode: replicated
      replicas: 3

  spark:
    image: maiktheknife/spark
    command: start-spark master
    hostname: sparkmaster
    networks:
      - backend
    depends_on:
      - namenode
    ports:
      - "6066:6066"
      - "7070:7070"
      - "8080:8080"
      - "50080:50070"
    deploy:
      mode: global

  edge:
    image: maiktheknife/edge
    tty: true # keep container without running main process
    networks:
      - backend
      - frontend
    depends_on:
      - spark

networks:
  frontend:
  backend:
