version: "3"

services:
  namenode:
    build: ./hadoop
    command: start-hadoop namenode
    hostname: namenode
    environment:
      HDFS_USER: hdfsuser
    volumes:
      - /d/docker/hdfs:/opt/hdfs/
      - /d/docker/logs:/usr/local/hadoop/current/logs/
    ports:
      - "22:22"
      - "8020:8020"
      - "8032:8032"
      - "8033:8033"
      - "8040:8040"
      - "8088:8088"
      - "14000:14000"
      - "50070:50070"
      - "50075:50075"
      - "10020:10020"
      - "13562:13562"
      - "19888:19888"

  datanode:
    build: ./hadoop
    command: start-hadoop datanode
    environment:
      HDFS_USER: hdfsuser
    depends_on:
      - namenode
#    volumes:
#      - dh:/opt/hdfs/
#      - dh:/usr/local/hadoop/current/logs/
#    deploy:
#      replicas: 3
#
#volumes:
#  dh: