version: "3"

services:
  namenode:
    build: ./hadoop
    command: start-hadoop namenode
    hostname: namenode
    environment:
      HDFS_USER: hdfsuser
      HDFS_GROUP: hdfsgroup
    volumes:
      - /d/docker/hdfs:/opt/hdfs/
      - /d/docker/logs:/usr/local/hadoop/current/logs/
    ports:
      - "8020:8020"
      - "14000:14000"
      - "50070:50070"
      - "50075:50075"
      - "10020:10020"
      - "13562:13562"
      - "19888:19888"

  datanode:
    build: ./hadoop
    command: start-hadoop datanode namenode
    environment:
      HDFS_USER: hdfsuser
      HDFS_GROUP: hdfsgroup
    depends_on:
      - namenode
    volumes:
      - /d/docker2/hdfs:/opt/hdfs/
      - /d/docker2/logs:/usr/local/hadoop/current/logs/
#    deploy:
#      replicas: 3
