version: "3"

services:
  namenode:
    image: maiktheknife/hadoop
    command: start-hadoop namenode
    hostname: namenode
    volumes:
      - /d/docker/hadoop/logs:/usr/local/hadoop/current/logs/
    ports:
      - "8020:8020"
      - "14000:14000"
      - "50070:50070"
      - "50075:50075"
      - "10020:10020"
      - "13562:13562"
      - "19888:19888"

  resourcemanager:
    image: maiktheknife/hadoop
    command: start-hadoop resourcemanager
    hostname: resourcemanager
    volumes:
      - /d/docker/yarn/logs:/usr/local/hadoop/current/logs/
    ports:
      - "8032:8032"
      - "8033:8033"
      - "8040:8040"
      - "8088:8088"

  datanode_nodemanager:
    image: maiktheknife/hadoop
    command: start-hadoop datanode
    depends_on:
      - resourcemanager
      - namenode

  edge:
    image: maiktheknife/edge
    tty: true # keep container without running main process
    depends_on:
      - resourcemanager